=== motadata2025/rum-events-format/schemas/telemetry/_common-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "telemetry/_common-schema.json",
  "title": "CommonTelemetryProperties",
  "type": "object",
  "description": "Schema of common properties of Telemetry events",
  "required": ["_md", "type", "date", "service", "source", "version"],
  "properties": {
    "_md": {
      "type": "object",
      "description": "Internal properties",
      "required": ["format_version"],
      "properties": {
        "format_version": {
          "type": "integer",
          "const": 2,
          "description": "Version of the RUM event format",
          "readOnly": true
        }
      }
    },
    "type": {
      "type": "string",
      "description": "Telemetry event type. Should specify telemetry only.",
      "const": "telemetry",
      "readOnly": true
    },
    "date": {
      "type": "integer",
      "description": "Start of the event in ms from epoch",
      "minimum": 0
    },
    "service": {
      "type": "string",
      "description": "The SDK generating the telemetry event"
    },
    "source": {
      "type": "string",
      "description": "The source of this event",
      "enum": ["android", "ios", "browser", "flutter", "react-native", "unity", "kotlin-multiplatform"],
      "readOnly": true
    },
    "version": {
      "type": "string",
      "description": "The version of the SDK generating the telemetry event"
    },
    "application": {
      "type": "object",
      "description": "Application properties",
      "required": ["id"],
      "properties": {
        "id": {
          "type": "string",
          "description": "UUID of the application",
          "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$"
        }
      },
      "readOnly": true
    },
    "session": {
      "type": "object",
      "description": "Session properties",
      "required": ["id"],
      "properties": {
        "id": {
          "type": "string",
          "description": "UUID of the session",
          "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$"
        }
      }
    },
    "view": {
      "type": "object",
      "description": "View properties",
      "required": ["id"],
      "properties": {
        "id": {
          "type": "string",
          "description": "UUID of the view",
          "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$"
        }
      }
    },
    "action": {
      "type": "object",
      "description": "Action properties",
      "required": ["id"],
      "properties": {
        "id": {
          "type": "string",
          "description": "UUID of the action",
          "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$"
        }
      }
    },
    "effective_sample_rate": {
      "type": "number",
      "description": "The actual percentage of telemetry usage per event",
      "minimum": 0,
      "maximum": 100
    },
    "experimental_features": {
      "type": "array",
      "description": "Enabled experimental features",
      "items": {
        "type": "string"
      },
      "readOnly": true
    },
    "telemetry": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "device": {
          "type": "object",
          "description": "Device properties",
          "properties": {
            "architecture": {
              "type": "string",
              "description": "Architecture of the device"
            },
            "brand": {
              "type": "string",
              "description": "Brand of the device"
            },
            "model": {
              "type": "string",
              "description": "Model of the device"
            }
          }
        },
        "os": {
          "type": "object",
          "description": "OS properties",
          "properties": {
            "build": {
              "type": "string",
              "description": "Build of the OS"
            },
            "name": {
              "type": "string",
              "description": "Name of the OS"
            },
            "version": {
              "type": "string",
              "description": "Version of the OS"
            }
          }
        }
      }
    }
  }
}

=== motadata2025/rum-events-format/samples/telemetry-events/debug.json
{
  "_md": {
    "format_version": 2
  },
  "type": "telemetry",
  "date": 1591284175342,
  "service": "sample-sdk",
  "source": "browser",
  "version": "1.2.3",
  "application": {
    "id": "ac8218cf-498b-4d33-bd44-151095959547"
  },
  "session": {
    "id": "cacbf45c-3a05-48ce-b066-d76349460599"
  },
  "view": {
    "id": "623d50fd-75cf-4025-97d2-e51ff94171f6"
  },
  "action": {
    "id": "ae3a5d82-cdd1-468d-9bc9-3aa9e54d953c"
  },
  "experimental_features": ["foo"],
  "telemetry": {
    "status": "debug",
    "message": "Session inconsistencies detected",
    "debug": {
      "comment": "All data in the telemetry object is forwarded"
    }
  }
}

=== motadata2025/rum-events-format/samples/telemetry-events/configuration.json
{
  "_md": {
    "format_version": 2
  },
  "type": "telemetry",
  "date": 1591284175342,
  "service": "sample-sdk",
  "source": "browser",
  "version": "1.2.3",
  "application": {
    "id": "ac8218cf-498b-4d33-bd44-151095959547"
  },
  "session": {
    "id": "cacbf45c-3a05-48ce-b066-d76349460599"
  },
  "view": {
    "id": "623d50fd-75cf-4025-97d2-e51ff94171f6"
  },
  "action": {
    "id": "ae3a5d82-cdd1-468d-9bc9-3aa9e54d953c"
  },
  "experimental_features": ["foo"],
  "telemetry": {
    "type": "configuration",
    "configuration": {
      "session_sample_rate": 100,
      "telemetry_sample_rate": 100,
      "telemetry_configuration_sample_rate": 5,
      "trace_sample_rate": 100,
      "trace_context_injection": "all",
      "session_replay_sample_rate": 100,
      "start_session_replay_recording_manually": true,
      "start_recording_immediately": true,
      "premium_sample_rate": 100,
      "replay_sample_rate": 100,
      "use_proxy": true,
      "use_before_send": true,
      "silent_multiple_init": false,
      "track_session_across_subdomains": true,
      "track_resources": true,
      "track_long_task": true,
      "track_bfcache_views": true,
      "use_cross_site_session_cookie": false,
      "use_secure_session_cookie": true,
      "session_persistence": "cookie",
      "action_name_attribute": "foo",
      "use_allowed_tracing_origins": false,
      "use_allowed_graph_ql_urls": false,
      "use_track_graph_ql_payload": false,
      "default_privacy_level": "mask",
      "text_and_input_privacy_level": "mask_all",
      "image_privacy_level": "mask_all",
      "touch_privacy_level": "hide",
      "enable_privacy_for_action_name": false,
      "use_excluded_activity_urls": false,
      "use_allowed_tracking_origins": false,
      "track_frustrations": true,
      "track_views_manually": true,
      "track_interactions": true,
      "track_user_interactions": true,
      "forward_console_logs": ["log", "debug"],
      "forward_errors_to_logs": false,
      "forward_reports": "all",
      "view_tracking_strategy": "ActivityViewTrackingStrategy",
      "swiftui_view_tracking_enabled": true,
      "swiftui_action_tracking_enabled": true,
      "track_background_events": true,
      "mobile_vitals_update_period": 10,
      "track_native_crashes": true,
      "plugins": [
        {
          "name": "foo",
          "option_foo": "bar"
        }
      ],
      "track_feature_flags_for_events": ["long_task", "resource", "vital"],
      "remote_configuration_id": "ae3a5d82-cdd1-468d-9bc9-3aa9e54d953c"
    }
  }
}

=== motadata2025/rum-events-format/samples/telemetry-events/usage.json
{
  "_md": {
    "format_version": 2
  },
  "type": "telemetry",
  "date": 1591284175342,
  "service": "sample-sdk",
  "source": "browser",
  "version": "1.2.3",
  "application": {
    "id": "ac8218cf-498b-4d33-bd44-151095959547"
  },
  "session": {
    "id": "cacbf45c-3a05-48ce-b066-d76349460599"
  },
  "view": {
    "id": "623d50fd-75cf-4025-97d2-e51ff94171f6"
  },
  "action": {
    "id": "ae3a5d82-cdd1-468d-9bc9-3aa9e54d953c"
  },
  "experimental_features": ["foo"],
  "telemetry": {
    "type": "usage",
    "usage": {
      "feature": "set-tracking-consent",
      "tracking_consent": "granted"
    }
  }
}
